### PR TITLE
Add support for red hat and misc fixes

### PR DESCRIPTION
**Pull request by pecigonzalo**
Tested on CentOS7 and RHEL 7

### CODE REVIEW

**Comment by pecigonzalo** [comment]
Closed pull request will re submit with fixes

**Comment by pecigonzalo** [comment]
The test for Debian is failing but i dont seem to be point at why. Once thats sorted ill add the same for RHEL (im new to the testing bits so i might require some help)

**Comment by Aethylred** [comment]
Right, I think the test suite needs updating since newer releases of `rspec-puppet`

**Comment by Aethylred** [comment]
Testing suite has been updated, could you please rebase against master.

**Pull request closed without merging**
