### PR TITLE
add two new parameters: node_terminus and external_nodes

### PR DESCRIPTION
**Pull request by tobru**
As the title says =)

### CODE REVIEW

**Comment by Aethylred** [comment]
Another good suggestion, but could you please to update the spec tests.

...including updating the whitespace correction you made for autosign.

**Comment by tobru** [comment]
New test added and the autosign whithespace fix test fixed =)

**Comment by tobru** [comment]
Hum, can't see why git is complaining about merge conflicts in README.markdown =( Maybe you see why it can't be merged without conflicts?

**Comment by tobru** [comment]
Ok, rebased to your master and now merging is possible again. Sorry for the noise...

**Pull request merged**
